version: '3'

vars:
  VERSION: '2.1.0'
  HUGO_BUILDOPTS: ''

tasks:
    default:
        desc: "Default task"
        cmds:
            - task: build

    build:
        desc: "Build the project"
        cmds:
            - echo "Building..."
            - hugo build

    serve:
        desc: "Serve the site locally with drafts"
        cmds:
            - hugo server --logLevel debug --disableFastRender --port 1314 --buildDrafts --buildFuture

    clean:
        desc: "Clean build artifacts"
        cmds:
            - echo "Cleaning..."
            - rm -rf public/

    deploy:
        desc: "Builds and pushes the umd-lib-opendata image"
        cmds:
            - docker buildx build --platform linux/amd64 --push -t docker.lib.umd.edu/opendata:{{.VERSION}} --build-arg HUGO_BUILDOPTS="{{.HUGO_BUILDOPTS}}" .

    test-python:
        desc: "Test all Python code examples in static/code/"
        cmds:
            - uv run test_python_examples.py
