version: '3'

tasks:
    serve:
        desc: "Serve the site"
        cmds:
            - echo "Serving the site..."
            - npx docusaurus start

    clean:
        desc: "Clean build artifacts"
        cmds:
            - echo "Cleaning build artifacts..."
            - npx docusaurus clear
